# Generated by Django 5.2.4 on 2025-07-14 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 14, 8, 12, 7, 787966, tzinfo=datetime.timezone.utc)),
        ),
    ]
