# Generated by Django 5.2.4 on 2025-07-14 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_ocrdocument_file_alter_ocrdocument_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrdocument',
            name='file',
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 14, 8, 13, 21, 371798, tzinfo=datetime.timezone.utc)),
        ),
    ]
