# Generated by Django 5.2.4 on 2025-07-18 12:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_ocrdocument_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='ocrdocument',
            name='type',
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='file_url',
            field=models.URLField(default='http://example.com/placeholder.pdf', max_length=255),
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='tag',
            field=models.CharField(default='general', max_length=255),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='name',
            field=models.CharField(default='untitled_document', max_length=255),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Document_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('box_text', models.TextField()),
                ('result_text', models.TextField()),
                ('edited_text', models.TextField(blank=True, null=True)),
                ('document_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='documents.ocrdocument')),
            ],
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='folder_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='documents.user'),
        ),
    ]
