# Generated by Django 5.2.4 on 2025-07-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_ocrdocument_file_alter_ocrdocument_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrdocument',
            name='file_url',
        ),
    ]
